pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Setup') {
            steps {
                wrap([$class: 'BuildUser']) {
                    script {
                        env.inputs = params.each { param -> return "${param.key} = ${param.value} " }
                    }
                }

            }
        }
        stage('Confirmation') {
            when {
                expression {
                    return params.Approve == false && params.Choice.equals("Run")
                }
            }
            steps {
                timeout(time: 5, unit: "MINUTES") {
                   input message: "Are you sure to proceed? 
                }
            }
        }


        stage('Run Python') {
            steps {
                sh 'python3 scripts/main.py'
            }
        }
    }
}
