pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Setup') {
                steps {
                    script {
                        env.Choice = params.Choice
                        env.Approve = params.Approve
                        echo "Build Parameters: choice -> ${env.Choice} approve -> ${env.Approve}"
                    }    
                }
        }

        stage('Confirmation') {
            when {
                expression {
                    return !params.Approve && params.Choice == "Run"
                }
            }
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    input(
                        message: 'Are you sure you want to proceed?',
                        ok: 'Proceed'
                    )
                }
            }
        }

        stage('Run Python') {
            steps {
                sh '''
                    pwd
                    ls -R
                    python3 scripts/main.py
                '''
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully.'
        }

        failure {
            echo 'Pipeline failed.'
        }

        always {
            echo 'Pipeline execution finished.'
        }
    }
}
