name: hello world
run-name: "Python Script - ${{ inputs.Choice }} / ${{ inputs.parameter }}"

on:
  workflow_dispatch:
    inputs:
      Choice:
        description: "Choice parameter"
        required: true
        type: choice
        options:
          - Run
          - Stop
      parameter:
        description: "parameter"
        required: true
        type: choice
        options:
          - start
          - Stop
jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run Python script
        env:
          Choice: ${{ inputs.Choice }}
          parameter: ${{ inputs.parameter }}
        run: |
          python scripts/main.py
